sudo: required
language: php

php:
  - '7.1'

branches:
  only:
  - gh-pages
  - /.*/

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - nvm install 7.4.0
  - npm install
  - composer install --no-interaction
  - npm install -g @angular/cli
  - cp .env.example .env
  - php artisan key:generate

script:
  - ng build --prod --aot=false
  - ng test --single-run
  - ./vendor/bin/phpunit

notifications:
  email: false
