language: php

php:
  - '7.1'

branches:
  only:
  - gh-pages
  - /.*/

before_script:
  - nvm install 7.4.0
  - npm install
  - composer install --no-interaction
  - npm install -g @angular/cli
  - cp .env.example .env
  - php artisan key:generate

script:
  - ng build --prod --aot=false
  - ng test --single-run
#  - ./vendor/bin/phpunit

notifications:
  email: false
