language: php

php:
  - '7.1'
  - '7.0'

branches:
  only:
  - gh-pages
  - /.*/

before_script:
  - nvm install 7.4.0
  - npm install
  - composer install
  - npm install -g @angular/cli
  - cp .env.example .env
  - php artisan key:generate
  - php artisan serve

script:
  - ng build --prod
