language: node_js

node_js:
  - 7.4.0

php:
  - 7.1
  - 7.0

branches:
  only:
  - gh-pages
  - /.*/

before_script:
  - npm install
  - composer install
  - npm install -g @angular/cli
  - php artisan key:generate
  - php artisan serve

script:
  - ng build --prod
